# Generated by Django 4.0.1 on 2022-01-23 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='nombre',
            new_name='nombres',
        ),
    ]
