# Generated by Django 4.0.1 on 2022-01-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_rename_nombre_usuarios_nombres'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
