# Generated by Django 4.0.1 on 2022-02-08 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_alter_usuarios_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuarios',
            table=None,
        ),
    ]
