# Generated by Django 4.0.1 on 2022-01-23 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_mascota', models.CharField(max_length=50, verbose_name='Nombre de la Mascota')),
                ('Telefono', models.CharField(max_length=10, unique=True, verbose_name='Número de telefono')),
                ('Fecha', models.DateTimeField(verbose_name='Fecha de la cita')),
                ('Sintomas', models.TextField(help_text='Aqui van los sintomas', max_length=2000, verbose_name='Sintomas')),
                ('Propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuarios')),
            ],
        ),
    ]
