# Generated by Django 4.0.2 on 2022-02-16 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_mascota', models.CharField(max_length=120, verbose_name='Nombre de la Mascota')),
                ('Telefono', models.CharField(max_length=10, verbose_name='Número de telefono')),
                ('Fecha', models.DateField(verbose_name='Fecha de la cita')),
                ('Sintomas', models.CharField(help_text='Aqui van los sintomas', max_length=2000, verbose_name='Sintomas')),
                ('Propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
            },
        ),
    ]
