# Generated by Django 4.0.1 on 2022-01-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='Fecha',
            field=models.DateField(verbose_name='Fecha de la cita'),
        ),
    ]
