# Generated by Django 4.0.1 on 2022-02-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0002_alter_citas_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citas',
            options={'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
        migrations.AlterField(
            model_name='citas',
            name='Nombre_mascota',
            field=models.CharField(max_length=120, verbose_name='Nombre de la Mascota'),
        ),
        migrations.AlterField(
            model_name='citas',
            name='Sintomas',
            field=models.CharField(help_text='Aqui van los sintomas', max_length=2000, verbose_name='Sintomas'),
        ),
    ]
