# Generated by Django 4.0.1 on 2022-02-07 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0003_alter_citas_options_alter_citas_nombre_mascota_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='citas',
            table='Citas',
        ),
    ]
