# Generated by Django 4.0.1 on 2022-02-08 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0004_alter_citas_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='citas',
            table=None,
        ),
    ]
