# Generated by Django 4.0.1 on 2022-02-03 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Citas', '0003_alter_citas_options_alter_citas_nombre_mascota_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('estado', models.CharField(max_length=150)),
                ('citas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Citas.citas')),
            ],
        ),
    ]
