# Generated by Django 4.0.1 on 2022-02-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tareas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tareas',
            options={'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
        migrations.AlterField(
            model_name='tareas',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=150),
        ),
        migrations.AlterModelTable(
            name='tareas',
            table='Tareas',
        ),
    ]
