# Generated by Django 4.0.1 on 2022-02-08 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tareas', '0003_alter_tareas_estado'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tareas',
            table=None,
        ),
    ]
